import {
  Body,
  Delete,
  Get,
  Param,
  Patch,
  Post,
  ParseUUIDPipe,
  Type,
  UsePipes,
  ValidationPipe,
} from '@nestjs/common';
import { CrudService } from '@/common/interfaces/crud-service.interface';
import { Paginate, Paginated } from 'nestjs-paginate';
import type { PaginateQuery } from 'nestjs-paginate';

/*
|--------------------------------------------------------------------------
| CrudControllerFactory
|--------------------------------------------------------------------------
|
| Factory function responsible for generating a reusable CRUD controller
| class with full runtime DTO awareness.
|
| This approach solves the limitation of TypeScript generics at runtime
| by explicitly passing DTO classes as values, allowing NestJS to:
| - Perform proper validation using ValidationPipe
| - Preserve clean, DRY controller implementations
| - Avoid method duplication across multiple controllers
|
| The returned controller class exposes standard CRUD endpoints and
| delegates all business logic to the provided CrudService implementation.
|
*/
export function CrudControllerFactory<Entity, CreateDto, UpdateDto>(
  CreateDtoClass: Type<CreateDto>,
  UpdateDtoClass: Type<UpdateDto>,
) {
  /*
  |------------------------------------------------------------------------
  | BaseCrudController (Generated)
  |------------------------------------------------------------------------
  |
  | Abstract controller generated by the factory.
  |
  | This controller:
  | - Contains no business logic
  | - Defines standard CRUD HTTP routes
  | - Applies validation pipes using runtime DTO classes
  |
  */
  abstract class BaseCrudController {
    /*
    |----------------------------------------------------------------------
    | constructor
    |----------------------------------------------------------------------
    |
    | Injects the CRUD service responsible for handling persistence
    | operations for the given entity.
    |
    | The service is exposed as a public readonly property to comply
    | with TypeScript restrictions on exported anonymous classes.
    |
    */
    protected constructor(
      public readonly service: CrudService<Entity, CreateDto, UpdateDto>,
    ) {}

    /*
    |----------------------------------------------------------------------
    | create
    |----------------------------------------------------------------------
    |
    | Creates a new entity using the provided creation DTO.
    |
    | Validation is applied explicitly using ValidationPipe with the
    | runtime CreateDto class to ensure class-validator decorators
    | are properly executed.
    |
    */
    @Post()
    @UsePipes(
      new ValidationPipe({
        whitelist: true,
        forbidNonWhitelisted: true,
        transform: true,
        expectedType: CreateDtoClass,
      }),
    )
    create(@Body() dto: CreateDto): Promise<Entity> {
      return this.service.create(dto);
    }

    /*
    |----------------------------------------------------------------------
    | findAll
    |----------------------------------------------------------------------
    |
    | Retrieves all entities of the given type.
    |
    */
    @Get()
    findAll(@Paginate() query: PaginateQuery): Promise<Paginated<Entity>> {
      return this.service.findAll(query);
    }

    /*
    |----------------------------------------------------------------------
    | findOne
    |----------------------------------------------------------------------
    |
    | Retrieves a single entity by its unique identifier (UUID).
    | Throws an error if the entity does not exist.
    |
    */
    @Get(':id')
    findOne(
      @Param('id', new ParseUUIDPipe({ version: '4' }))
      id: string,
    ): Promise<Entity> {
      return this.service.findOne(id);
    }

    /*
    |----------------------------------------------------------------------
    | update
    |----------------------------------------------------------------------
    |
    | Updates an existing entity using the provided update DTO.
    |
    | Validation is applied explicitly using ValidationPipe with the
    | runtime UpdateDto class.
    |
    */
    @Patch(':id')
    @UsePipes(
      new ValidationPipe({
        whitelist: true,
        forbidNonWhitelisted: true,
        transform: true,
        expectedType: UpdateDtoClass,
      }),
    )
    update(
      @Param('id', new ParseUUIDPipe({ version: '4' }))
      id: string,
      @Body() dto: UpdateDto,
    ): Promise<Entity> {
      return this.service.update(id, dto);
    }

    /*
    |----------------------------------------------------------------------
    | remove
    |----------------------------------------------------------------------
    |
    | Permanently deletes an entity by its identifier (UUID).
    |
    */
    @Delete(':id')
    remove(
      @Param('id', new ParseUUIDPipe({ version: '4' }))
      id: string,
    ): Promise<void> {
      return this.service.remove(id);
    }
  }

  return BaseCrudController;
}
